version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  
  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync .next/static s3://${WEBSITE_BUCKET_NAME}/_next/static
      - aws s3 cp .next/standalone/. s3://${WEBSITE_BUCKET_NAME}/ --recursive

artifacts:
  base-directory: .next
  files:
    - '**/*' 